### PR TITLE
Fix SEGFAULT from calling FT_New_Face/FT_Done_Face in multiple threads

### LINKED ISSUE #8454: Segfault under free-threaded build
See https://github.com/tonybaloney/pytest-freethreaded/issues/9 where this was discovered and for steps to reproduce.

Ultimately this comes down to the thread safety warnings in the freetype docs for `FT_Face`: https://freetype.org/freetype2/docs/reference/ft2-face_creation.html#ft_face. Somehow an `FT_Face` is being shared across threads in the test scenario linked above.

Ping @lysnikolaou

### PR DESCRIPTION
**Pull request by lysnikolaou**
Fixes #8454.

Changes proposed in this pull request:

 * Introduce a mutex that needs to be held every time `FT_New_Face` or `FT_Done_Face` are called.
 * Upgrade `pythoncapi_compat.h` to the latest version.

### CODE REVIEW

**Review by hugovk — APPROVED** [review]
Thanks!

File: src/thirdparty/pythoncapi_compat.h [hunk 1]
```diff
@@ -7,7 +7,10 @@
 // https://github.com/python/pythoncapi_compat
 //
 // Latest version:
-// https://raw.githubusercontent.com/python/pythoncapi_compat/master/pythoncapi_compat.h
+// https://raw.githubusercontent.com/python/pythoncapi-compat/main/pythoncapi_compat.h
+//
+// This file was vendored from the following commit:
+// https://github.com/python/pythoncapi-compat/commit/0041177c4f348c8952b4c8980b2c90856e61c7c7
```
Comment (nulano) [inline src/thirdparty/pythoncapi_compat.h:13]: This commit appears to be already merged in the latest version of this file.

**Review by nulano — COMMENTED** [review]
Is anything here actually using the new changes in `pythoncapi_compat.h`?

There's no reason to stick with an old version, but I'm curious if there is a reason for updating it in what looks like an unrelated PR?

File: src/thirdparty/pythoncapi_compat.h (hunk 1 above)
Comment (lysnikolaou) [reply src/thirdparty/pythoncapi_compat.h:13]: This is what I wanted to convey in my comment. That the version of the file came from this specific commit.

Comment (nulano) [reply src/thirdparty/pythoncapi_compat.h:13]: Ah, I see now, thanks for the explanation.

File: src/_imagingft.c [hunk 2]
```diff
@@ -1639,6 +1648,7 @@ PyInit__imagingft(void) {
     }
 
 #ifdef Py_GIL_DISABLED
+    ft_library_mutex = (PyMutex){0};
```
[the remark this answers is not in the document]
Comment (lysnikolaou) [reply src/_imagingft.c]: That's because assignment without a cast is not possible when it's not initialization.

We can actually get rid of assigning to the mutex altogether by declaring the `PyMutex` as static, which is the recommended way and what needs to be done here. Sorry I missed this and thanks for pointing it out.

File: src/_imagingft.c [hunk 3]
```diff
@@ -82,6 +82,9 @@ struct {
     /* font objects */
 
     static FT_Library library;
+#ifdef Py_GIL_DISABLED
+static PyMutex ft_library_mutex;
```
Comment (nulano) [inline src/_imagingft.c:86]:
```suggestion
static PyMutex ft_library_mutex = {0};
```
?

**Review by radarhere — APPROVED** [review]

File: src/_imagingft.c (hunk 2 above)
[the remark this answers is not in the document]
Comment (radarhere) [reply src/_imagingft.c]: Just for more information, could you link to that recommendation? I'm not seeing anything explicit at https://docs.python.org/3/c-api/init.html#synchronization-primitives

[the remark this answers is not in the document]
Comment (lysnikolaou) [reply src/_imagingft.c]: The recommendation is in a header comment in the CPython code [here](https://github.com/python/cpython/blob/dc76a4ad3c46af3fb70361be10b8a791cd126931/Include/cpython/lock.h#L15).
