### PR TITLE
PCX encoding fixes

### LINKED ISSUE #2023: PCX encoder produces corrupted files
This is the image in `P` mode which becomes corrupted if resave it in PCX.

_temp

```python
from PIL import Image
Image.open('_temp.png').save('_temp.pcx')
Image.open('_temp.pcx').load()
```

```
/home/homm/Code/Pillow/PIL/ImageFile.pyc in load(self)
    238         if not self.map and not LOAD_TRUNCATED_IMAGES and err_code < 0:
    239             # still raised if decoder fails to return anything
--> 240             raise_ioerror(err_code)
    241 
    242         # post processing

/home/homm/Code/Pillow/PIL/ImageFile.pyc in raise_ioerror(error)
     57     if not message:
     58         message = "decoder error %d" % error
---> 59     raise IOError(message + " when reading image file")
     60 
     61 

IOError: buffer overrun when reading image file
```

The issue is in PCX encoder, not in decoder because Photoshop also opens PCX file with glitches:

_temp copy

### PR DESCRIPTION
**Pull request by homm**
Fixes #2023.

### CODE REVIEW

File: libImaging/PcxEncode.c [hunk 1]
```diff
@@ -152,33 +154,34 @@ ImagingPcxEncode(Imaging im, ImagingCodecState state, UINT8* buf, int bytes)
...
                 }
                 /* reset for the next color plane. */
                 if (state->x < planes * bytes_per_line) {
                     state->count = 1;
                     state->LAST = state->buffer[state->x];
-                    state->x++;
+                    state->x += 1;
                 }
-            }
+            } while (state->x < planes * bytes_per_line);
```
Comment (homm) [inline libImaging/PcxEncode.c]: This is the only significant change.

**Comment by homm** [comment]
Appveyor OK: https://ci.appveyor.com/project/Python-pillow/pillow/build/3.4.pre.1368
Coverage increased +0.03%: https://coveralls.io/builds/7197043
