### PR TITLE
Fix Screengrab DPI scaling on Windows 10 version 1607+

### LINKED ISSUE #2438: Enable DPI Scaling Awareness
### What did you do?
Tried to grab a screenshot with pyautogui.  This passes control over to Pillow's imagegrab.

### What did you expect to happen?
A screenshot of the entire screen.

### What actually happened?
The top left corner of the screen (1/4) was saved.

### What versions of Pillow and Python are you using?
Python 3.6, Pillow 4.00

Please include code that reproduces the issue and whenever possible, an image that demonstrates the issue. The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, django, or buildout, try to replicate the issue just using Pillow. 

```python
PIL.ImageGrab.grab(bbox=None)
<PIL.Image.Image image mode=RGB size=1600x900 at 0x132A0D5F898>
# screen resolution is actually 3200x1800
```

Fix - making the App DPI Aware:
https://github.com/asweigart/pyautogui/issues/33#issuecomment-236981496

### PR DESCRIPTION
**Pull request by nulano**
Fixes #2438 and its duplicates #3432, #3626 for Windows 10 version 1607+ (Anniversary Update).

This PR uses [`SetThreadDpiAwarenessContext`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setthreaddpiawarenesscontext) to temporarily make Python DPI aware. This function returns the previous awareness context, which is then used to restore the old value, thus avoiding problems with other parts of Python. It was added in Windows 10 version 1607, which is why it is called dynamically.

The issue is not fixed for older versions of Windows. This is not a big problem for Windows 7, as *very* few people use DPI scaling there. Windows 8 and Windows 10 pre-1607 are now out of standard support by Microsoft.

### CODE REVIEW

File: src/display.c [hunk 1]
```diff
@@ -329,6 +331,9 @@ PyImaging_GrabScreenWin32(PyObject* self, PyObject* args)
     HDC screen, screen_copy;
     DWORD rop;
     PyObject* buffer;
+    HANDLE dpiAwareness;
+	HMODULE user32 = LoadLibraryA("User32.dll");
+	Func_SetThreadDpiAwarenessContext SetThreadDpiAwarenessContext_function;
```
Comment (nulano) [inline src/display.c]: Can someone suggest a better name here? This the best I could do but it's ridiculously long.

Comment (hugovk) [reply src/display.c]: At least it's descriptive! :)

**Comment by hugovk** [comment]
PR 4000! 🍰
