### PR TITLE
Fixed linear_gradient and radial_gradient I and F modes

### LINKED ISSUE #5272: Segmentation fault when creating gradient images with mode "F"
### What did you do?
```pycon
Python 3.9.1 (default, Jan 13 2021, 15:21:08) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PIL
>>> print(PIL.__version__)
8.0.1
>>> import PIL.Image as pimage
>>> image1 = pimage.linear_gradient("L")
>>> image2 = pimage.linear_gradient("F")
Segmentation fault
```

### What did you expect to happen?
Not segfaulting.

### What actually happened?
Segfaulted.

### What are your OS, Python and Pillow versions?

* OS: Red Hat 4.8.5-44
* Python: Python 3.9.1
* Pillow: 8.0.1

### PR DESCRIPTION
**Pull request by radarhere**
Resolves #5272

`Image.linear_gradient("I")`, `Image.linear_gradient("F")`, `Image.radial_gradient("I")` and `Image.radial_gradient("F")` all currently segfault. This fixes them.

### CODE REVIEW

File: src/libImaging/Fill.c [hunk 1]
```diff
@@ -76,8 +76,21 @@ ImagingFillLinearGradient(const char *mode) {
...
-        memset(im->image8[y], (unsigned char)y, 256);
+    if (im->image8) {
+        for (y = 0; y < 256; y++) {
+            memset(im->image8[y], (unsigned char)y, 256);
+        }
+    } else {
+        int x;
+        for (y = 0; y < 256; y++) {
+            for (x = 0; x < 256; x++) {
+                if (im->type == IMAGING_TYPE_FLOAT32) {
```
Comment (hugovk) [inline src/libImaging/Fill.c:87]: Does refactoring this check outside the `256 * 256` loop make any sort of performance difference?

Comment (wiredfool) [reply src/libImaging/Fill.c:87]: Branch prediction should be bang on for this one. And I'd even expect that the compiler would hoist this.
