### PR TITLE
Use explicit memcpy() to avoid unaligned memory accesses

### LINKED ISSUE #3213: Unaligned access crash
The test suite crashes when run on sparc machines at several places because of SIGBUS errors, i.e. unaligned memory accesses. This usually affects also other platforms (ARM, Itanium), but to a lesser degree (often only slowdown and no crashes).

I have a unfinished patch, currently targetting 4.3.0 as that is what is my current problem in Gentoo. A port to master and PR will follow later once I get the testsuite to pass again.

Further details and preliminary patch at https://bugs.gentoo.org/659460

### PR DESCRIPTION
**Pull request by DerDakon**
Fixes #3213.

This replaces casts of incoming memory with explicit memcpy(). Some platforms, especially Sparc, but also ARM and Itanium, do not like unaligned memory accesses and may lack from slowdowns or crashes as result of those if the incoming memory is not aligned to the expected access type. Using memcpy() will avoid this: the compiler will optimize this to direct unaligned accesses on platforms that support those operations, and will do whatever copy operation is needed on platforms that do not.

### CODE REVIEW

**Comment by homm** [comment]
Personally, I don't like it because, while compiler *will likely* optimize `memcpy` calls to just one move operation, it *doesn't have to* optimize it.

Do you have examples of such fixes in other wide-spread libraries?

**Comment by DerDakon** [comment]
Is [python](https://github.com/python/cpython/pull/6123) common enough? For fixed size copies you must try very hard for the compiler not to optimize this on e.g. x86, this is one of the most common intrinsics that are in use.

**Comment by DerDakon** [comment]
Ping?

**Comment by DerDakon** [comment]
Ping?

**Comment by DerDakon** [comment]
Ping?

**Comment by DerDakon** [comment]
What is the way forward? I bet this needs updating, but I'm only going to do this if it would be accepted afterwards.

**Comment by DerDakon** [comment]
ping?

**Comment by DerDakon** [comment]
I would rebase it if there is a chance that this get's merged in time then, otherwise it is too much work for nothing.

**Comment by hugovk** [comment]
There's been no objections from @homm or anyone else in a year, so let's merge this for Monday's release, if possible. Thank you!

File: src/libImaging/Unpack.c [hunk 1]
```diff
@@ -480,86 +479,78 @@ void
 ImagingUnpackRGB(UINT8* _out, const UINT8* in, int pixels)
 {
     int i = 0;
-#ifdef __sparc
-    /* SPARC CPUs cannot read integers from nonaligned addresses. */
```
Comment (hugovk) [inline src/libImaging/Unpack.c]: Are the removals of these exceptions for SPARC intentional?

They were only added recently, in https://github.com/python-pillow/Pillow/pull/3858.

Comment (DerDakon) [reply src/libImaging/Unpack.c]: Yes, by using memcpy the compiler will care for the correct access pattern.

Comment (hugovk) [reply src/libImaging/Unpack.c]: OK, thanks.

cc @kulikjak fyi.

**Comment by DerDakon** [comment]
I have tested this on my sparc machine and I see some test errors. I guess test errors and I suspect them being endianess issues. I guess this is still better than crashes. I'll probably need a few days to look into this.

**Comment by DerDakon** [comment]
Ok, I was even faster than expected. When I compare the test results of my patch on sparc with current git master on hppa I have only these additional failures:

Tests/test_imagefont.py::TestImageFont::test_variation_get FAILED
Tests/test_imagefont.py::TestImageFont::test_variation_set_by_axes FAILED
Tests/test_imagefont.py::TestImageFont::test_variation_set_by_name FAILED

Please decide if they are likely caused by this patches or not, I have no clue.

**Comment by DerDakon** [comment]
I have tested it on my hppa machine (also big endian) with and without this patch, and the font errors are also present there in both runs. So I don't see any regressions with that patch.

**Comment by hugovk** [comment]
Thanks for testing. As no regressions found, let's merge it.
