### PR TITLE
Fix coefficients calculation

### LINKED ISSUE #2161: Pillow 3.4 breaks Image.thumbnail
### What did you do?
```python
    img = Image.open("test.png")
    img.thumbnail((256, 256))
    img.save("output.png")
```
### What did you expect to happen?
Create a thumbnail.

### What actually happened?
It creates a thumbnail with random transparent lines all over it.

### What versions of Pillow and Python are you using?
Python 3.5 and Pillow 3.4.1. With Pillow 3.3.3 it works perfectly.

test

output

### PR DESCRIPTION
**Pull request by homm**
Fixes #2161.

### CODE REVIEW

**Comment by homm** [comment]
Please note, this is PR for `3.4` branch. We also need it in master.

**Comment by hugovk** [comment]
Looks good:
output

Is there a test you could add to guard against future regressions?

**Comment by homm** [comment]
@hugovk test added

File: libImaging/Resample.c [hunk 1]
```diff
@@ -184,7 +184,6 @@ precompute_coeffs(int inSize, int outSize, struct filter *filterp,
                 } else if (x == xmax - 1) {
                     xmax -= 1;
                 }
-                continue;
             }
             k[x] = w;
```
Comment (wiredfool) [inline libImaging/Resample.c]: Is this bug a case of using uninitialized memory?  It kind of looks that way from the non-deterministic pattern of the alpha in the bug.

Would initializing all the coefficients to 0 have prevented this?

Comment (homm) [inline libImaging/Resample.c]: > Is this bug a case of using uninitialized memory?

Yes

> Would initializing all the coefficients to 0 have prevented this?

Yes. Actually, I was certain that all memory is initialized:

1. `kk` has size of `outSize` * `kmax` doubles;
2. `xbounds` has size of two `outSize` ints;
3. We iterate `xx` from 0 to `outSize` in outer loop, so we initialize whole `xbounds`;
4. We iterate `x` in inner loop from 0 to `xmax` and initialize it with some coefficient `w`;
5. Then iterate `x` from current `x`(`xmax`) to `kmax`, and initialize it with zeroes.

So, `kk` and `xbounds` should be guaranteed initialized. The bug was on the fourth step: there was a `continue`, so on some conditions, some `kk` elements were not initialized.

Comment (homm) [inline libImaging/Resample.c]: Hmm, but such uninitialized values should be outside of `xmax`. I need 10 minutes to investigate why this leads to the bug.

Comment (wiredfool) [inline libImaging/Resample.c]: Yeah, I'm not seeing how that happens. xmax should be decremented on any 0 coefficient, and then the last loop should go from that decremented xmax to kmax. 

It does look like a calloc instead of malloc would solve all the initialization problems in one less math prone statement:
```
    kk = calloc(outSize * kmax , sizeof(double));
```

Comment (homm) [inline libImaging/Resample.c]: > It does look like a calloc instead of malloc would solve all the initialization problems

This is true for this case. Of course, it would be better to initialize memory one extra time than get a bug. But I think it is unnecessary for now when we exactly know what everything is initialized. I also eliminated the last `continue` from this code.

**Comment by homm** [comment]
@wiredfool Are you happy with the current fix. I'm afraid this is a perfect candidate for v3.4.2. Sorry for this.
